apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-pvc
  namespace: go
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
  namespace: go
  labels:
    app: keycloak-postgresql
type: Opaque
data:
  postgresql-password: ZWEzMTE4OWZlMWU2YzgxMzRhMzkwODM2YmRjZDk3YTlmZDBlY2M0NTMwMGIwYmQ0NmI0NGE3OWIyMWRh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgresql
  namespace: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgresql
  template:
    metadata:
      labels:
        app: keycloak-postgresql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:15.2
          env:
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
  namespace: go
spec:
  selector:
    app: keycloak-postgresql
  ports:
    - port: 5432
