apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploygo
  namespace: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploygo
      version: "v1"
  template:
    metadata:
      labels:
        app: deploygo
        version: "v1"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - deploygo
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - "/bin/sh"
            - "-c"
            - |
              while true
              do
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: deploygo-app
          image: lokeshkarakala/deploygo
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            # - name: MINIKUBE_IP
            #   valueFrom:
            #     configMapKeyRef:
            #       name: minikube-cm
            #       key: minikube-ip
            - name: MANAGEMENT_TRACING_BAGGAGE_REMOTE_FIELDS
              value: "x-request-id,x-ot-span-context"
            # Custom trustStore required when using Let's Encrypt staging
            - name: JAVA_OPTS
              value: " -Xmx256m -Xms256m"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI
              value: http://192.168.49.2:30001/realms/jhipster
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID
              value: internal
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET
              value: internal
            - name: SERVER_SHUTDOWN
              value: graceful
            # Custom trustStore required when using Let's Encrypt staging
            # volumeMounts:
            #  - name: java-truststore
            #    mountPath: /etc/pki/java
            ## GO ##
            - name: KEYCLOAK_URL
              value: http://192.168.49.2:30001/realms/jhipster
            - name: SERVICE_REGISTRY_URL
              value: http://admin:$(JHIPSTER_REGISTRY_PASSWORD)@jhipster-registry.go.svc.cluster.local:8761/eureka/apps/
              ## GO MICRO ##
            - name: GO_MICRO_ACTIVE_PROFILE
              value: prod
            - name: GO_MICRO_KEYCLOAK_URL
              value: http://192.168.49.2:30001
            - name: GO_MICRO_SERVICE_REGISTRY_URL
              value: http://admin:$(JHIPSTER_REGISTRY_PASSWORD)@jhipster-registry.go.svc.cluster.local:8761/eureka/apps/
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - name: http
              containerPort: 9454
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 120
