apiVersion: v1
kind: Service
metadata:
  name: deploygo
  namespace: go
  labels:
    app: deploygo
spec:
  selector:
    app: deploygo
  ports:
    - name: http
      port: 80
      targetPort: 9454
