commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: go

resources:
  - namespace.yml
  # Individual apps
  - deploygo-k8s/deploygo-deployment.yml
  - deploygo-k8s/deploygo-service.yml
  # keycloak
  - keycloak-k8s/keycloak-configmap.yml
  - keycloak-k8s/keycloak-postgresql.yml
  - keycloak-k8s/keycloak.yml
# service discovery eureka/consul

patchesJson6902:
