apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: lokeshkarakala/deploygo
      context: ../deploygo
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
